SELECT D3.ID
FROM ECOLI_DATA D3
JOIN (SELECT D2.ID
      FROM ECOLI_DATA D2
      JOIN (SELECT D1.ID
            FROM ECOLI_DATA D1
            WHERE D1.PARENT_ID IS NULL 
           ) D ON D.ID = D2.PARENT_ID 
     ) DD ON DD.ID = D3.PARENT_ID
ORDER BY D3.ID