SELECT GEN3.ID
FROM ECOLI_DATA GEN3 
JOIN (SELECT GEN.ID
    FROM ECOLI_DATA GEN JOIN (SELECT ID
                        FROM ECOLI_DATA
                        WHERE PARENT_ID IS NULL) GEN1
    ON GEN.PARENT_ID=GEN1.ID) GEN2
ON GEN3.PARENT_ID=GEN2.ID