SELECT P.PRODUCT_CODE, P.PRICE *  S.AMOUNT AS SALES
FROM PRODUCT P
JOIN
(SELECT *, SUM(SALES_AMOUNT) AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) S
ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC