SELECT P.PRODUCT_CODE, S.AMOUNT * P.PRICE AS SALES
FROM PRODUCT P
JOIN 
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) S
ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
