SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN
(SELECT R1.FOOD_TYPE AS TY, MAX(R1.FAVORITES) AS FAV
FROM REST_INFO R1
GROUP BY R1.FOOD_TYPE) R2 
ON R.FAVORITES = R2.FAV AND R.FOOD_TYPE =R2.TY 
ORDER BY R.FOOD_TYPE DESC