SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
WHERE (R.FOOD_TYPE, R.FAVORITES) IN (SELECT R1.FOOD_TYPE, MAX(R1.FAVORITES)
                                    FROM REST_INFO R1
                                    GROUP BY R1.FOOD_TYPE)
ORDER BY R.FOOD_TYPE DESC