SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM (SELECT * FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME LIKE "%Neutered%" OR SEX_UPON_OUTCOME LIKE '%Spayed%') OUTS 
JOIN 
(SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE "%Intact%") INS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID