SELECT H.HISTORY_ID, ROUND(C.DAILY_FEE *(DATEDIFF(H.END_DATE, H.START_DATE)+1)*(1-(IFNULL(P.DISCOUNT_RATE, 0)/100)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    LEFT JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON
    (CASE 
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1>=90) THEN '90일 이상'
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1>=30) THEN '30일 이상'
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1>=7) THEN '7일 이상'
        END) = P.DURATION_TYPE
    AND P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC