SELECT U.USER_ID, U.NICKNAME, T.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT B.WRITER_ID, SUM(B.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    WHERE B.STATUS LIKE "DONE"
    GROUP BY B.WRITER_ID
    HAVING TOTAL_SALES>=700000
    
) T 
ON U.USER_ID = T.WRITER_ID
ORDER BY TOTAL_SALES