SELECT YEAR(E1.DIFFERENTIATION_DATE) YEAR, ABS(E1.SIZE_OF_COLONY-E2.MAX_SIZE) AS YEAR_DEV, E1.ID
FROM ECOLI_DATA E1
JOIN (
    SELECT YEAR(E3.DIFFERENTIATION_DATE) Y, MAX(E3.SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA E3
    GROUP BY YEAR(E3.DIFFERENTIATION_DATE)
) E2
ON YEAR(E1.DIFFERENTIATION_DATE) = E2.Y
ORDER BY YEAR, YEAR_DEV